n1 = int(input())
n2 = int(input())
n3 = int(input())
n4 = int(input())
soma = int(n1+n2+n3+n4)
produto = int(n1*n2*n3*n4)
print(f"A soma dos números é:{soma}")
print(f"O produto dos números é:{produto}")